version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: serveeaze-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: serveeaze-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: "npm run dev" # Use 'start' in production

volumes:
  mongo-data:
